#!/bin/bash
#SBATCH --job-name=aorl
#SBATCH --open-mode=append
#SBATCH -o /global/scratch/users/jenniferzhao/logs/%A_%a.out
#SBATCH -e /global/scratch/users/jenniferzhao/logs/%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --mem=40G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:A5000:1
#SBATCH --account=co_rail
#SBATCH --partition=savio4_gpu
#SBATCH --qos=rail_gpu4_lowest
#SBATCH --requeue
#SBATCH --array=1-32%100
#SBATCH --comment=2026-03-03-00-part1

TASK_ID=$((SLURM_ARRAY_TASK_ID-1))
PARALLEL_N=1
JOB_N=32

COM_ID_S=$((TASK_ID * PARALLEL_N + 1))
# module load gnu-parallel
source ~/.bashrc
micromamba activate aorl


declare -a commands=(
  [1]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [2]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [3]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [4]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [5]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [6]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [7]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [8]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=1 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [9]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [10]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [11]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [12]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [13]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [14]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [15]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [16]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=4 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [17]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [18]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [19]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [20]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [21]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [22]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [23]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [24]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=8 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [25]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [26]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=1.0'
  [27]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [28]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0'
  [29]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [30]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=30.0'
  [31]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
  [32]='MUJOCO_GL=egl python fql_baseline.py --run_group=2026-03-03-00_debug --offline_steps=50 --further_offline_steps=50 --collection_steps=50 --eval_episodes=1 --video_episodes=0 --eval_interval=5 --save_interval=25 --data_plot_interval=25 --log_interval=25 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/fql.py --agent.best_of_n=16 --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=300.0'
)

parallel --delay 5s --linebuffer -j 1 {1} ::: "${commands[@]:$COM_ID_S:$PARALLEL_N}"
            