#!/bin/bash

# List of scripts to run
scripts=(
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=50 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=100 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=600.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=1200.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=1001 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=2002 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=25 --use_rnd_bonus=False"
  "MUJOCO_GL=egl python triangle_inequality.py --run_group=2026-04-08-00 --offline_steps=1000000 --further_offline_steps=2000000 --collection_steps=1000000 --save_interval=100000 --eval_interval=50000 --cleanup=True --seed=3003 --env_name=humanoidmaze-large-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-large-navigate-v0 --agent=agents/dqc.py --agent.train_goal_proposer=True --agent.backup_horizon=25 --agent.policy_chunk_size=1 --agent.kappa_b=0.5 --agent.kappa_d=0.8 --agent.num_qs=10 --agent.q_agg=mean --agent.discount=0.995 --agent.batch_size=256 --agent.best_of_n=4 --fql_agent=agents/fql.py --fql_agent.best_of_n=4 --fql_agent.horizon_length=25 --fql_agent.action_chunking=False --fql_agent.num_qs=10 --fql_agent.q_agg=mean --fql_agent.discount=0.995 --fql_agent.batch_size=256 --fql_agent.alpha=300.0 --triangle_percentile=25 --use_rnd_bonus=False"
)

# List of available GPU IDs (modify as needed)
gpus=(0 1 2 4 5 6 7)

num_gpus=${#gpus[@]}
num_scripts=${#scripts[@]}

# Store PIDs of background jobs
pids=()

# Function to handle Ctrl+C
cleanup() {
  echo "Terminating all running processes..."
  for pid in "${pids[@]}"; do
    kill "$pid" 2>/dev/null
  done
  wait
  exit 1
}

# Trap SIGINT (Ctrl+C) and call cleanup
trap cleanup SIGINT

# Function to run scripts sequentially on a given GPU
run_on_gpu() {
  local gpu_id=$1
  shift
  local gpu_scripts=("$@")

  for script in "${gpu_scripts[@]}"; do
    echo "Running $script on GPU $gpu_id"
    CUDA_VISIBLE_DEVICES=$gpu_id eval "$script" &
    pids+=($!)  # Store PID of the process
    wait ${pids[-1]}  # Wait for the process to finish before moving to the next
  done
}

# Distribute scripts among GPUs
for ((i=0; i<num_gpus; i++)); do
  gpu_scripts=()

  # Assign every nth script to this GPU
  for ((j=i; j<num_scripts; j+=num_gpus)); do
    gpu_scripts+=("${scripts[j]}")
  done

  if [ ${#gpu_scripts[@]} -gt 0 ]; then
    run_on_gpu ${gpus[i]} "${gpu_scripts[@]}" &
    pids+=($!)  # Store PID of background process
  fi
done

wait  # Wait for all background jobs
echo "All scripts finished."
