#!/bin/bash
#SBATCH --job-name=aorl
#SBATCH --open-mode=append
#SBATCH -o /global/scratch/users/jenniferzhao/logs/%A_%a.out
#SBATCH -e /global/scratch/users/jenniferzhao/logs/%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --mem=40G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:A5000:1
#SBATCH --account=co_rail
#SBATCH --partition=savio4_gpu
#SBATCH --qos=rail_gpu4_high
#SBATCH --requeue
#SBATCH --array=1-45%100
#SBATCH --comment=2026-03-12-part1

TASK_ID=$((SLURM_ARRAY_TASK_ID-1))
PARALLEL_N=1
JOB_N=45

COM_ID_S=$((TASK_ID * PARALLEL_N + 1))
# module load gnu-parallel
source ~/.bashrc
micromamba activate aorl


declare -a commands=(
  [1]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [2]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [3]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task3-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [4]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task4-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [5]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=humanoidmaze-medium-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [6]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=cube-triple-play-singletask-task1-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [7]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=cube-triple-play-singletask-task2-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [8]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=cube-triple-play-singletask-task3-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [9]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=cube-triple-play-singletask-task4-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [10]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=cube-triple-play-singletask-task5-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [11]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=antmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [12]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=antmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [13]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=antmaze-medium-navigate-singletask-task3-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [14]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=antmaze-medium-navigate-singletask-task4-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [15]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=1001 --env_name=antmaze-medium-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [16]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [17]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [18]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=humanoidmaze-medium-navigate-singletask-task3-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [19]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=humanoidmaze-medium-navigate-singletask-task4-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [20]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=humanoidmaze-medium-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [21]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=cube-triple-play-singletask-task1-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [22]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=cube-triple-play-singletask-task2-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [23]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=cube-triple-play-singletask-task3-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [24]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=cube-triple-play-singletask-task4-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [25]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=cube-triple-play-singletask-task5-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [26]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=antmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [27]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=antmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [28]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=antmaze-medium-navigate-singletask-task3-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [29]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=antmaze-medium-navigate-singletask-task4-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [30]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=2002 --env_name=antmaze-medium-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [31]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=humanoidmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [32]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=humanoidmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [33]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=humanoidmaze-medium-navigate-singletask-task3-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [34]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=humanoidmaze-medium-navigate-singletask-task4-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [35]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=humanoidmaze-medium-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/humanoidmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.995 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [36]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=cube-triple-play-singletask-task1-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [37]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=cube-triple-play-singletask-task2-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [38]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=cube-triple-play-singletask-task3-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [39]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=cube-triple-play-singletask-task4-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [40]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=cube-triple-play-singletask-task5-v0 --dataset_dir=../../scratch/data/cube-triple-play-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=True --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [41]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=antmaze-medium-navigate-singletask-task1-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [42]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=antmaze-medium-navigate-singletask-task2-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [43]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=antmaze-medium-navigate-singletask-task3-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [44]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=antmaze-medium-navigate-singletask-task4-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
  [45]='MUJOCO_GL=egl python train_value.py --run_group=2026-03-12 --offline_steps=100000 --eval_interval=10000 --save_interval=50000 --log_interval=1000 --cleanup=True --seed=3003 --env_name=antmaze-medium-navigate-singletask-task5-v0 --dataset_dir=../../scratch/data/antmaze-medium-navigate-v0 --agent=agents/gcfql.py --agent.train_value=True --agent.horizon_length=25 --agent.action_chunking=False --agent.num_qs=10 --agent.q_agg=min --agent.discount=0.99 --agent.batch_size=256 --agent.alpha=3.0 --agent.critic_loss_type=bce'
)

parallel --delay 5s --linebuffer -j 1 {1} ::: "${commands[@]:$COM_ID_S:$PARALLEL_N}"
            