#!/bin/bash
#SBATCH --job-name=aorl
#SBATCH --open-mode=append
#SBATCH -o /global/scratch/users/jenniferzhao/logs/%A_%a.out
#SBATCH -e /global/scratch/users/jenniferzhao/logs/%A_%a.err
#SBATCH --time=10:00:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:A5000:1
#SBATCH --account=co_rail
#SBATCH --partition=savio4_gpu
#SBATCH --qos=rail_gpu4_high
#SBATCH --requeue
#SBATCH --array=1-8%16
#SBATCH --signal=B:USR1@90

TASK_ID=$((SLURM_ARRAY_TASK_ID-1))
PARALLEL_N=2
JOB_N=16

COM_ID_S=$((TASK_ID * PARALLEL_N + 1))
source ~/.bashrc
micromamba activate aorl
export PYTHONPATH="../:${PYTHONPATH}"

declare -a commands=(
 [1]='python3 e2e.py --run_group e2e_maze_8_1 --seed 0 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [2]='python3 e2e.py --run_group e2e_maze_8_1 --seed 0 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [3]='python3 e2e.py --run_group e2e_maze_8_1 --seed 0 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [4]='python3 e2e.py --run_group e2e_maze_8_1 --seed 0 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [5]='python3 e2e.py --run_group e2e_maze_8_1 --seed 1 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [6]='python3 e2e.py --run_group e2e_maze_8_1 --seed 1 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [7]='python3 e2e.py --run_group e2e_maze_8_1 --seed 1 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [8]='python3 e2e.py --run_group e2e_maze_8_1 --seed 1 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [9]='python3 e2e.py --run_group e2e_maze_8_1 --seed 2 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [10]='python3 e2e.py --run_group e2e_maze_8_1 --seed 2 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [11]='python3 e2e.py --run_group e2e_maze_8_1 --seed 2 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [12]='python3 e2e.py --run_group e2e_maze_8_1 --seed 2 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [13]='python3 e2e.py --run_group e2e_maze_8_1 --seed 3 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [14]='python3 e2e.py --run_group e2e_maze_8_1 --seed 3 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
 [15]='python3 e2e.py --run_group e2e_maze_8_1 --seed 3 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 10000 --video_episodes 0 --eval_episodes 0'
 [16]='python3 e2e.py --run_group e2e_maze_8_1 --seed 3 --env_name humanoidmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/humanoidmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=False --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --wrapper wrappers/withrnd.py --wrapper.max_episode_steps 2000 --wrapper.pre_init=True --offline_steps 100 --collection_steps 2000000 --video_episodes 0 --eval_episodes 0'
)

cd /home/jennifer/aorl/horizon_reduction

parallel --delay 20 --linebuffer -j 2 {1} ::: "${commands[@]:$COM_ID_S:$PARALLEL_N}"
