#!/bin/bash
#SBATCH --job-name=aorl
#SBATCH --open-mode=append
#SBATCH -o /global/scratch/users/jenniferzhao/logs/%A_%a.out
#SBATCH -e /global/scratch/users/jenniferzhao/logs/%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:A5000:1
#SBATCH --account=co_rail
#SBATCH --partition=savio4_gpu
#SBATCH --qos=rail_gpu4_lowest
#SBATCH --requeue
#SBATCH --array=1-12%16

TASK_ID=$((SLURM_ARRAY_TASK_ID-1))
PARALLEL_N=2
JOB_N=24

COM_ID_S=$((TASK_ID * PARALLEL_N + 1))
source ~/.bashrc
micromamba activate aorl
export PYTHONPATH="../:${PYTHONPATH}"

declare -a commands=(
 [1]='python3 e2e.py --run_group e2e_maze_4_3 --seed 0 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid mi3yirzm'
 [2]='python3 e2e.py --run_group e2e_maze_4_3 --seed 0 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 8iweetrw'
 [3]='python3 e2e.py --run_group e2e_maze_4_3 --seed 0 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 56orcf2h'
 [4]='python3 e2e.py --run_group e2e_maze_4_3 --seed 0 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 6lzvokym'
 [5]='python3 e2e.py --run_group e2e_maze_4_3 --seed 0 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid eq0mfivm'
 [6]='python3 e2e.py --run_group e2e_maze_4_3 --seed 0 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid w2u9ntse'
 [7]='python3 e2e.py --run_group e2e_maze_4_3 --seed 1 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 44h9kvz8'
 [8]='python3 e2e.py --run_group e2e_maze_4_3 --seed 1 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid ij3mcq9d'
 [9]='python3 e2e.py --run_group e2e_maze_4_3 --seed 1 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid g0ovyev8'
 [10]='python3 e2e.py --run_group e2e_maze_4_3 --seed 1 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid emt4mlzm'
 [11]='python3 e2e.py --run_group e2e_maze_4_3 --seed 1 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 7jbsljue'
 [12]='python3 e2e.py --run_group e2e_maze_4_3 --seed 1 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid qdga85hl'
 [13]='python3 e2e.py --run_group e2e_maze_4_3 --seed 2 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid rgkx9qg1'
 [14]='python3 e2e.py --run_group e2e_maze_4_3 --seed 2 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 0rcqplcf'
 [15]='python3 e2e.py --run_group e2e_maze_4_3 --seed 2 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 3r86hzct'
 [16]='python3 e2e.py --run_group e2e_maze_4_3 --seed 2 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid nuvmpok7'
 [17]='python3 e2e.py --run_group e2e_maze_4_3 --seed 2 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid qunapraw'
 [18]='python3 e2e.py --run_group e2e_maze_4_3 --seed 2 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 6j05b86j'
 [19]='python3 e2e.py --run_group e2e_maze_4_3 --seed 3 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid ajq5lse7'
 [20]='python3 e2e.py --run_group e2e_maze_4_3 --seed 3 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid tiq9wp2f'
 [21]='python3 e2e.py --run_group e2e_maze_4_3 --seed 3 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 100000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 8b8t582o'
 [22]='python3 e2e.py --run_group e2e_maze_4_3 --seed 3 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 50 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid bbcfmvst'
 [23]='python3 e2e.py --run_group e2e_maze_4_3 --seed 3 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 100 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid 4mk3fx84'
 [24]='python3 e2e.py --run_group e2e_maze_4_3 --seed 3 --env_name antmaze-medium-navigate-oraclerep-v0 --agent ../agents/gcfql.py --dataset_dir ../../scratch/data/antmaze-medium-navigate-v0 --train_data_size 1000000 --save_dir ../../scratch --offline_steps 100 --save_interval 50 --log_interval 100 --eval_interval 50 --eval_episodes 0 --video_episodes 0 --agent.alpha 300 --agent.actor_type best-of-n --agent.train_goal_proposer=True --agent.goal_proposer_type default --agent.subgoal_steps 200 --agent.actor_hidden_dims 512,512,512,512 --agent.value_hidden_dims 512,512,512,512 --agent.batch_size 256 --agent.num_actions 8 --agent.num_qs 10 --agent.q_agg mean --agent.discount 0.995 --data_option datafuncs/withsubgoal.py --data_option.collection_steps 100 --data_option.save_data_interval 50 --data_option.plot_interval 50 --data_option.max_episode_steps 20  --wbid o38n4l1o'
)

cd /home/jennifer/aorl/horizon_reduction

parallel --delay 20 --linebuffer -j 2 {1} ::: "${commands[@]:$COM_ID_S:$PARALLEL_N}"
